BEGIN TRANSACTION;
CREATE TABLE Ore (id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, ref INTEGER NOT NULL, unitVolume DOUBLE PRECISION NOT NULL, unitPrice DOUBLE PRECISION NOT NULL, discr VARCHAR(255) NOT NULL, id_primaryOre INTEGER DEFAULT NULL, PRIMARY KEY(id));
INSERT INTO `Ore` VALUES (1,'Veldspar',0,0.1,10.0,'primary',NULL);
INSERT INTO `Ore` VALUES (2,'Concentrated Veldspar',1,0.1,11.0,'secondary',1);
INSERT INTO `Ore` VALUES (3,'Dense Veldspar',2,0.1,11.0,'secondary',1);
CREATE INDEX IDX_A4569D4C4643D4C7 ON Ore (id_primaryOre);
COMMIT;
